//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mpvnet.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mpvnet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///name = process-instance
        ///file = mpvnet
        ///default = single
        ///filter = General
        ///help = Defines if more then one mpv.net process is allowed. (mpv.net specific option)\n\nMulti can alternatively be enabled by pressing the SHIFT key.\n\nWhenever the control key is pressed when files or URLs are opened, the playlist is not cleared but the files or URLs are appended to the playlist. This not only works on process startup but in all mpv.net features that open files and URLs.
        ///option = multi   Create a new process e [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string editor_conf {
            get {
                return ResourceManager.GetString("editor_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///  {
        ///    &quot;Path&quot;: &quot;Open \u003E Open Files...&quot;,
        ///    &quot;Command&quot;: &quot;script-message-to mpvnet open-files&quot;,
        ///    &quot;Display&quot;: &quot;Open \u003E Open Files...&quot;,
        ///    &quot;Input&quot;: &quot;o&quot;,
        ///    &quot;Alias&quot;: null
        ///  },
        ///  {
        ///    &quot;Path&quot;: &quot;Open \u003E Open URL or file from clipboard&quot;,
        ///    &quot;Command&quot;: &quot;script-message-to mpvnet open-clipboard&quot;,
        ///    &quot;Display&quot;: &quot;Open \u003E Open URL or file from clipboard&quot;,
        ///    &quot;Input&quot;: &quot;V&quot;,
        ///    &quot;Alias&quot;: null
        ///  },
        ///  {
        ///    &quot;Path&quot;: &quot;Open \u003E Open DVD/Blu-ray Drive/Folder...&quot;,
        ///    &quot;Command&quot;: &quot;scrip [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///# https://github.com/mpvnet-player/mpv.net/blob/master/docs/Manual.md#input-and-context-menu
        ///
        ///o           script-message-to mpvnet open-files         #menu: Open &gt; Open Files...
        ///V           script-message-to mpvnet open-clipboard     #menu: Open &gt; Open URL or file from clipboard
        ///_           script-message-to mpvnet open-optical-media #menu: Open &gt; Open DVD/Blu-ray Drive/Folder...
        ///_           ignore                                      #menu: Open &gt; -
        ///Alt+a       script-message-to mpvnet load-audio   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string input_conf {
            get {
                return ResourceManager.GetString("input_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap mpvnet {
            get {
                object obj = ResourceManager.GetObject("mpvnet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap mpvnet_santa {
            get {
                object obj = ResourceManager.GetObject("mpvnet_santa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///[dark]
        ///
        ///heading     = #3C8CC8
        ///foreground  = #DDDDDD
        ///foreground2 = #AAAAAA
        ///background  = #323232
        ///highlight   = #404040
        ///
        ///menu-foreground = #DDDDDD
        ///menu-background = #323232
        ///menu-highlight  = #505050
        ///
        ///
        ///[light]
        ///
        ///heading     = #0068B2
        ///foreground  = #000000
        ///foreground2 = #4C4C4C
        ///background  = #F7F7F7
        ///highlight   = #DFDFDF
        ///
        ///menu-foreground = #000000
        ///menu-background = #DFDFDF
        ///menu-highlight  = #BFBFBF
        /// 的本地化字符串。
        /// </summary>
        internal static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
    }
}
